In [2]:
import numpy as np
# The main object is the homogenous multidimensional arrays. Tables of same type elements

In [48]:
# Creating an Array
nums = np.array([(4, 5, 6, 7, 8), (4, 8, 6, 9, 8), (45, 6, 8, 3, 45)])
print(nums)
type(nums) # Checking the type
print('***********')
print(nums.sum()) # FInds the sum of all the elements in the ndarray
nums.min() / nums.max()
print(nums.std()) # Standard deviation. You don't have to import the math module to accomplish this..

[[ 4  5  6  7  8]
 [ 4  8  6  9  8]
 [45  6  8  3 45]]
***********
172
13.260802724152443


In [30]:
print(nums.shape) # Finding the shape of an array
print(nums.dtype)

(3, 5)
int32


In [23]:
one = nums[2, -1]
print(one)
two = nums[2, 2]
print(two)

45
8


In [27]:
print(sum(nums))

[53 19 20 19 61]


In [28]:
print(nums.sum(axis=1)) # Adding the rows together
print("----------")
print(nums.sum(axis=0)) # Adding the columns

[ 30  35 107]
----------
[53 19 20 19 61]


In [117]:
jig = nums.reshape(5, 3) # Reshaping the array
print(jig)

[[ 4  5  6]
 [ 7  8  4]
 [ 8  6  9]
 [ 8 45  6]
 [ 8  3 45]]


In [135]:
print(jig[1:3, :]) #Slicing the array. Rows and cols needed
print('---------')
print(jig[2:, 1:])
print('--------')
print(jig[::-1]) #  Prints the array in reverse order. Last row as first and V.V.

[[7 8 4]
 [8 6 9]]
---------
[[ 6  9]
 [45  6]
 [ 3 45]]
--------
[[ 8  3 45]
 [ 8 45  6]
 [ 8  6  9]
 [ 7  8  4]
 [ 4  5  6]]


In [134]:
print(jig[1::3]) # Prints rows from index 1 to end, skipping to every other third row
print('--------')
print(jig[2::2]) # Prints from index 2 to end, skipping to every other second row

[[ 7  8  4]
 [ 8  3 45]]
--------
[[ 8  6  9]
 [ 8  3 45]]


In [30]:
add = sum(nums)
print(add)

[35 67 70]


In [31]:
print(nums.sum(axis=1)) # Adding the rows together
print("----------")
print(nums.sum(axis=0)) # Adding the columns

[15 19 23 59 56]
----------
[35 67 70]


In [46]:
names = np.linspace(100, 1000, 10)
print(names)

[ 100.  200.  300.  400.  500.  600.  700.  800.  900. 1000.]


In [49]:
likes = np.linspace(10, 100, 10) # Printing the specified num of nums between the given range 
print(likes)
twice= np.linspace(1, 10, 10)
print(twice)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [41]:
you = np.arange(2, 5) # Print nums between 2 and 5 but not including 5
print(you)

[2 3 4]


In [49]:
you = np.arange(20, 25) # Print nums between 20 and 25 but not including 25
print(you)

[20 21 22 23 24]


In [4]:
hates = np.array([(23, 45, 654, 34, 56), (34, 76, 87, 56, 45), (67, 45, 645, 34, 56)])
print(hates)

[[ 23  45 654  34  56]
 [ 34  76  87  56  45]
 [ 67  45 645  34  56]]


In [50]:
print(hates[1, 2])
hates[-1, -1] # The last row, the last column..

87


56

In [30]:
you = hates.reshape(5, 3)
print(you)

[[ 23  45 654]
 [ 34  56  34]
 [ 76  87  56]
 [ 45  67  45]
 [645  34  56]]


In [41]:
print(you[2, 1])
print(you[4, 0])

87
645


In [55]:
print(you.ndim)
print(you.dtype)
print(you.size)
print(you.itemsize)

1
int32
5
4


In [60]:
friends = np.array([('You', 'Me', 'Them'), ('Me', 'Them', 'Her'), ('Jose', 'Kim', 'Zach')])
print(friends)

[['You' 'Me' 'Them']
 ['Me' 'Them' 'Her']
 ['Jose' 'Kim' 'Zach']]


In [123]:
names = np.array([(True, False, True), (False, True, True)])
print(names)
print(names.dtype)

[[ True False  True]
 [False  True  True]]
bool


In [70]:
# An example of built-in methods to create arrays
np.ones((3, 4), dtype=np.int16) # Three rows and 4 cols all ones.

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [76]:
print(np.full((4, 5), 34)) # The first argument specifies the rows and cols. The 2nd, the value to fill them.
print('*********************')
print(np.full((5, 6), 1.1))

[[34 34 34 34 34]
 [34 34 34 34 34]
 [34 34 34 34 34]
 [34 34 34 34 34]]
*********************
[[1.1 1.1 1.1 1.1 1.1 1.1]
 [1.1 1.1 1.1 1.1 1.1 1.1]
 [1.1 1.1 1.1 1.1 1.1 1.1]
 [1.1 1.1 1.1 1.1 1.1 1.1]
 [1.1 1.1 1.1 1.1 1.1 1.1]]


In [82]:
# Printing the nums in a given range
np.arange(24, 76, 10) # First and second args specify the starting and end point
# the third arg specifies the difference between the values
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [83]:
np.full((3, 4), False)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [84]:
np.full((3, 4), True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [128]:
her = np.full((3, 4), 'Hae')
print(her)
print(her.size)

[['Hae' 'Hae' 'Hae' 'Hae']
 ['Hae' 'Hae' 'Hae' 'Hae']
 ['Hae' 'Hae' 'Hae' 'Hae']]
12


In [90]:
np.random.rand(2, 3) # Spits out random floats between 0 and 1 to fill all the rows and cols

array([[0.79023393, 0.17022669, 0.9286041 ],
       [0.50629798, 0.07495389, 0.88266665]])

In [88]:
np.random.rand(3, 4)

array([[0.33904945, 0.58589729, 0.97666715, 0.42753354],
       [0.89795474, 0.48237673, 0.89662567, 0.50607337],
       [0.52849161, 0.42558825, 0.66996426, 0.79857633]])

In [3]:
np.empty((4, 3)) # Check on this

array([[7.87810304e-312, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.11260619e-306, 3.59790104e+179],
       [1.76104018e-076, 3.89488707e-033, 3.27360878e+179],
       [1.00611400e-046, 1.65753052e-076, 5.26602809e-037]])

In [5]:
# Create a 2x2 identity matrix
id = np.eye(3, 3)
id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
id2 = np.eye(5, 5)
id2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [138]:
a = np.array([1, 2, 3, 4, 5]) # Numpy Array

In [139]:
b = [1, 2, 3, 4, 5] # Regular python array(list)
print(b)

[1, 2, 3, 4, 5]


In [140]:
a[1:3] = 10 # You can change multiple values at once
a

array([ 1, 10, 10,  4,  5])

In [144]:
b[1:3] = 10 # For normal python arrays. This will throw an error... Can only assign an iterable

In [3]:
array = np.array([10, 20, 30, 40, 50, 60])
array

array([10, 20, 30, 40, 50, 60])

In [5]:
a_slice = array[1:4].copy() # You have to use the copy() method in numpy to copy a slice of an array without modifying the original one
a_slice

array([20, 30, 40])

In [6]:
a_slice = array[1:4] # See if you do not use it, the original array is modified as well...
a_slice[1:3] = 1000
a_slice

array([  20, 1000, 1000])

In [6]:
# Numpy so called broadcasting rules...
print(np.arange(3))
print('**********************')
np.arange(3) + np.ones((3,3))

[0 1 2]
**********************


array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [7]:
np.arange(3) + 5 # A range of three + 5. I believe it increments automatically...

array([5, 6, 7])

In [10]:
print(np.arange(3).reshape(3, 1))
print('*************')
np.arange(3).reshape(3,1) + np.arange(3) # I believe it increments each row by the range given after reshape..

[[0]
 [1]
 [2]]
*************


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [14]:
print(np.ones((3,3))) # Ones...
print('**************')
np.ones((4, 4)) + np.arange(4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
**************


array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [19]:
a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
b = np.array([(2), (2), (2)])
print(a)
print('************')
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
************
[2 2 2]


In [20]:
print(a + b)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
# Accessing rows using boolean values...
a = np.arange(12).reshape(3, 4) # Range of 12 (0 -11)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
rows_on = np.array([True, False, True]) # First set the boolean array to be used in accessing the rows..
rows_on

array([ True, False,  True])

In [28]:
a[rows_on , 2: ] # Set the boolean array as the indexing for getting the rows..

array([[ 2,  3],
       [10, 11]])

In [34]:
# Shit getting real yoh...
# USing numpy to solve a system of linear equations
# 2x + 6y = 6 -----(i)
# 5x + 3y = -9 -----(ii)

coeffs = np.array([[2, 6], [5, 3]])
depvars = np.array([6, -9])
solution = linalg.solve(coeffs, depvars)
solution

NameError: name 'linalg' is not defined

In [9]:
nums = np.array([23, 45, 65, 76, 45, 45])
nums

array([23, 45, 65, 76, 45, 45])

In [3]:
nums_slice = nums[1:4] # Slicing a ndarray and storing the result in as another ndarray
nums_slice

array([45, 65, 76])

In [4]:
# Modfying the slice of the original array modifies the original one as well
nums_slice[2] = 1000
nums_slice

array([  45,   65, 1000])

In [5]:
nums # Changing a value of the slice also changes it in the original array

array([  23,   45,   65, 1000,   45,   45])

In [10]:
# To ensure the above does not occur.. Use the copy() function
nums_slice = nums[1:4].copy()
nums_slice # FRom original Nums array

array([45, 65, 76])

In [11]:
# After using the copy() function, changing a value ensures the original array stays intact
nums_slice[2] = 7777
nums_slice

array([  45,   65, 7777])

In [12]:
nums #  See, the 7777 did not replace the 1000...

array([23, 45, 65, 76, 45, 45])

In [13]:
np.full((4,7), 'Crap')

array([['Crap', 'Crap', 'Crap', 'Crap', 'Crap', 'Crap', 'Crap'],
       ['Crap', 'Crap', 'Crap', 'Crap', 'Crap', 'Crap', 'Crap'],
       ['Crap', 'Crap', 'Crap', 'Crap', 'Crap', 'Crap', 'Crap'],
       ['Crap', 'Crap', 'Crap', 'Crap', 'Crap', 'Crap', 'Crap']],
      dtype='<U4')